/**
 * ReportGeneratorEngine - Service for generating lab reports in multiple formats
 * Generates PDF, HTML, and text reports with customizable templates and branding
 * 
 * Week 2 Phase 1 - RobotCom LIMS Automation Project
 * Author: David Navas
 */

export interface ReportConfig {
  labName: string;
  labLogo?: string;
  customText1?: string;
  customText2?: string;
  reportFormat: 'PDF' | 'HTML' | 'TEXT';
  includeNormalRanges: boolean;
  includeInterpretation: boolean;
  includeGraphs: boolean;
  includeQCData: boolean;
  footerText?: string;
}

export interface ReportContent {
  format: string;
  content: string;
  mimeType: string;
  filename: string;
}

export interface PatientInfo {
  patientID: string;
  firstName: string;
  lastName: string;
  dateOfBirth: Date;
  gender: string;
  phone?: string;
  email?: string;
  address?: string;
}

export interface SampleInfo {
  sampleNumber: string;
  collectionDate: Date;
  receivedDate: Date;
  sampleType: string;
  condition?: string;
}

export interface TestResult {
  testId: string;
  testName: string;
  value: number | string;
  unit: string;
  normalRange?: string;
  abnormalStatus?: 'NORMAL' | 'LOW' | 'HIGH' | 'CRITICAL_LOW' | 'CRITICAL_HIGH';
  interpretation?: string;
  referenceRange?: string;
}

/**
 * ReportGeneratorEngine creates formatted laboratory reports for various outputs
 * Supports multiple formats: PDF, HTML, and plaintext
 */
export class ReportGeneratorEngine {
  /**
   * Generate HTML report
   */
  static generateHTMLReport(
    patientInfo: PatientInfo,
    sampleInfo: SampleInfo,
    results: TestResult[],
    config: ReportConfig
  ): ReportContent {
    const labName = config.labName;
    const customText1 = config.customText1 || '';
    const customText2 = config.customText2 || '';
    const patientID = patientInfo.patientID;
    const footerText = config.footerText || 'This is an automated report generated by RobotCom LIMS';

    let html = '<!DOCTYPE html>\n';
    html += '<html lang="en">\n<head>\n';
    html += '<meta charset="UTF-8">\n';
    html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    html += `<title>Laboratory Report - ${patientID}</title>\n`;
    html += '<style>\n';
    html += 'body { margin: 0; padding: 0; font-family: Arial, sans-serif; }\n';
    html += '.container { max-width: 900px; margin: 0 auto; padding: 20px; }\n';
    html += '.header { border-bottom: 3px solid #0066cc; padding-bottom: 20px; margin-bottom: 20px; }\n';
    html += 'table { width: 100%; border-collapse: collapse; margin: 20px 0; }\n';
    html += 'th { background: #0066cc; color: white; padding: 12px; text-align: left; }\n';
    html += 'td { padding: 12px; border-bottom: 1px solid #ddd; }\n';
    html += '.footer { margin-top: 30px; text-align: center; color: #999; font-size: 11px; }\n';
    html += '</style>\n</head>\n<body>\n<div class="container">\n';

    // Header
    html += '<div class="header">\n';
    html += `<h1>${labName}</h1>\n`;
    html += `<p>${customText1}</p>\n`;
    html += `<p>${customText2}</p>\n`;
    html += `<p>Report Date: ${new Date().toLocaleString()}</p>\n`;
    html += '</div>\n';

    // Patient Info
    html += '<h2>Patient Information</h2>\n';
    html += '<table>\n<tr><td><strong>Patient ID:</strong></td><td>' + patientInfo.patientID + '</td></tr>\n';
    html += '<tr><td><strong>Name:</strong></td><td>' + patientInfo.firstName + ' ' + patientInfo.lastName + '</td></tr>\n';
    html += '<tr><td><strong>DOB:</strong></td><td>' + patientInfo.dateOfBirth.toLocaleDateString() + '</td></tr>\n';
    html += '<tr><td><strong>Gender:</strong></td><td>' + patientInfo.gender + '</td></tr>\n';
    html += '</table>\n';

    // Sample Info
    html += '<h2>Sample Information</h2>\n';
    html += '<table>\n<tr><td><strong>Sample:</strong></td><td>' + sampleInfo.sampleNumber + '</td></tr>\n';
    html += '<tr><td><strong>Collected:</strong></td><td>' + sampleInfo.collectionDate.toLocaleString() + '</td></tr>\n';
    html += '<tr><td><strong>Received:</strong></td><td>' + sampleInfo.receivedDate.toLocaleString() + '</td></tr>\n';
    html += '</table>\n';

    // Results
    html += '<h2>Laboratory Results</h2>\n';
    html += '<table><thead><tr><th>Test</th><th>Value</th><th>Unit</th>';
    if (config.includeNormalRanges) html += '<th>Normal Range</th>';
    html += '</tr></thead><tbody>\n';

    results.forEach((result) => {
      html += '<tr><td>' + result.testName + '</td>';
      html += '<td>' + result.value + '</td>';
      html += '<td>' + result.unit + '</td>';
      if (config.includeNormalRanges) {
        html += '<td>' + (result.normalRange || 'N/A') + '</td>';
      }
      html += '</tr>\n';
    });

    html += '</tbody></table>\n';
    html += '<div class="footer">\n';
    html += '<p>' + footerText + '</p>\n';
    html += '</div>\n</div>\n</body>\n</html>\n';
    return {
      format: 'HTML',
      content: html,
      mimeType: 'text/html',
      filename: `Report_${patientInfo.patientID}_${new Date().getTime()}.html`,
    };
  }

  /**
   * Generate plain text report
   */
  static generateTextReport(
    patientInfo: PatientInfo,
    sampleInfo: SampleInfo,
    results: TestResult[],
    config: ReportConfig
  ): ReportContent {
    let text = '';
    text += `${'='.repeat(80)}\n`;
    text += `${config.labName.toUpperCase()}\n`;
    text += `${config.customText1 || ''}\n`;
    text += `${config.customText2 || ''}\n`;
    text += `Report Generated: ${new Date().toLocaleString()}\n`;
    text += `${'='.repeat(80)}\n\n`;

    text += `PATIENT INFORMATION\n`;
    text += `${'-'.repeat(80)}\n`;
    text += `Patient ID: ${patientInfo.patientID}\n`;
    text += `Name: ${patientInfo.firstName} ${patientInfo.lastName}\n`;
    text += `Date of Birth: ${patientInfo.dateOfBirth.toLocaleDateString()}\n`;
    text += `Gender: ${patientInfo.gender}\n`;
    if (patientInfo.phone) text += `Phone: ${patientInfo.phone}\n`;
    if (patientInfo.email) text += `Email: ${patientInfo.email}\n`;
    text += '\n';

    text += `SAMPLE INFORMATION\n`;
    text += `${'-'.repeat(80)}\n`;
    text += `Sample Number: ${sampleInfo.sampleNumber}\n`;
    text += `Collection Date: ${sampleInfo.collectionDate.toLocaleString()}\n`;
    text += `Received Date: ${sampleInfo.receivedDate.toLocaleString()}\n`;
    text += `Sample Type: ${sampleInfo.sampleType}\n`;
    text += '\n';

    text += `LABORATORY RESULTS\n`;
    text += `${'-'.repeat(80)}\n`;
    text += `${this.padString('TEST', 40)} ${this.padString('VALUE', 15)} UNIT\n`;
    if (config.includeNormalRanges) text += `${this.padString('NORMAL RANGE', 65)}\n`;
    text += `${'-'.repeat(80)}\n`;

    results.forEach((result) => {
      let line = `${this.padString(result.testName, 40)} ${this.padString(String(result.value), 15)} ${result.unit}`;
      let status = '';

      if (result.abnormalStatus === 'CRITICAL_LOW' || result.abnormalStatus === 'CRITICAL_HIGH') {
        status = ' [CRITICAL]';
      } else if (result.abnormalStatus === 'LOW' || result.abnormalStatus === 'HIGH') {
        status = ' [ABNORMAL]';
      }

      text += `${line}${status}\n`;

      if (config.includeNormalRanges && result.normalRange) {
        text += `  Normal Range: ${result.normalRange}\n`;
      }

      if (config.includeInterpretation && result.interpretation) {
        text += `  Interpretation: ${result.interpretation}\n`;
      }
    });

    text += '\n';
    text += `${config.footerText || 'This is an automated report generated by RobotCom LIMS'}\n`;
    text += `${'='.repeat(80)}\n`;

    return {
      format: 'TEXT',
      content: text,
      mimeType: 'text/plain',
      filename: `Report_${patientInfo.patientID}_${new Date().getTime()}.txt`,
    };
  }

  /**
   * Generate CSV report for data export
   */
  static generateCSVReport(
    patientInfo: PatientInfo,
    sampleInfo: SampleInfo,
    results: TestResult[]
  ): ReportContent {
    let csv = '';

    // Header
    csv += `"Patient ID","Name","DOB","Gender","Sample Number","Collection Date","Sample Type"\n`;
    csv += `"${patientInfo.patientID}","${patientInfo.firstName} ${patientInfo.lastName}",`;
    csv += `"${patientInfo.dateOfBirth.toLocaleDateString()}","${patientInfo.gender}",`;
    csv += `"${sampleInfo.sampleNumber}","${sampleInfo.collectionDate.toLocaleString()}",`;
    csv += `"${sampleInfo.sampleType}"\n\n`;

    // Results
    csv += `"Test Name","Value","Unit","Normal Range","Status","Interpretation"\n`;
    results.forEach((result) => {
      csv += `"${result.testName}","${result.value}","${result.unit}",`;
      csv += `"${result.normalRange || ''}","${result.abnormalStatus || 'NORMAL'}",`;
      csv += `"${result.interpretation || ''}"\n`;
    });

    return {
      format: 'CSV',
      content: csv,
      mimeType: 'text/csv',
      filename: `Report_${patientInfo.patientID}_${new Date().getTime()}.csv`,
    };
  }

  /**
   * Helper function to pad strings for alignment
   */
  private static padString(str: string, length: number): string {
    const padding = ' '.repeat(Math.max(0, length - str.length));
    return str + padding;
  }

  /**
   * Validate report configuration
   */
  static validateReportConfig(config: Partial<ReportConfig>): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!config.labName) {
      errors.push('Lab name is required');
    }

    if (!config.reportFormat) {
      errors.push('Report format must be specified (PDF, HTML, or TEXT)');
    } else if (!['PDF', 'HTML', 'TEXT', 'CSV'].includes(config.reportFormat)) {
      errors.push('Invalid report format. Must be PDF, HTML, TEXT, or CSV');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Get report MIME type
   */
  static getMimeType(format: string): string {
    const mimeTypes: { [key: string]: string } = {
      PDF: 'application/pdf',
      HTML: 'text/html',
      TEXT: 'text/plain',
      CSV: 'text/csv',
    };
    return mimeTypes[format.toUpperCase()] || 'application/octet-stream';
  }

  /**
   * Create default report configuration
   */
  static createDefaultConfig(labName: string, format: 'PDF' | 'HTML' | 'TEXT' = 'HTML'): ReportConfig {
    return {
      labName,
      reportFormat: format,
      includeNormalRanges: true,
      includeInterpretation: true,
      includeGraphs: false,
      includeQCData: false,
    };
  }
}

export default ReportGeneratorEngine;
